spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:/Users/alexsuch/Downloads/patientmanagement/database;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2
graphql:
  servlet:
    corsEnabled: true
    enabled: true
    mapping: /graphql